version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

  node:
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  node-network:
    driver: bridge